// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgnuutetlmpsflimzida.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnbnV1dGV0bG1wc2ZsaW16aWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0ODc0MDQsImV4cCI6MjA2MzA2MzQwNH0.bHF87l2AdISAMZV62QxQw_wMh9y0hQvP24l2QpElfFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);